global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # Set a global scrape timeout
  scrape_timeout: 10s

# External labels for multi-environment support
external_labels:
  environment: 'production'
  project: 'vh-banquets'

# Alerting rules (uncomment and create alert.rules.yml if needed)
rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

# Retention policy (set via Prometheus command line, shown here for reference)
# To use: add '--storage.tsdb.retention.time=15d' to Prometheus command in docker-compose.yml

scrape_configs:
  - job_name: 'nginx-frontend'
    static_configs:
      - targets: ['nginx-exporter:9113']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: frontend
    # Add job-specific scrape timeout
    scrape_timeout: 5s

  - job_name: 'backend-api'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: backend
    scrape_timeout: 5s

  - job_name: 'cadvisor-metrics'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: cadvisor
    scrape_timeout: 5s

# For more info, see https://prometheus.io/docs/prometheus/latest/configuration/configuration/
